### ISSUE TITLE
Mildom: READ THIS BEFORE DOWNLOADING

### ISSUE THREAD

**Issue by nao20010128nao** [nao20010128nao/ytdl-patched#22]
# TL;DR
Notify me before downloading VODs a lot! Bandwidth exceeded!

(also available at https://github.com/yt-dlp/yt-dlp/issues/251)

# Mildom extractor use proxy at Vercel
A game-oriented live website, [Mildom](https://mildom.com) serves the video over HTTP with HLS protocol (as youtube-dl/ytdl-patched's term).    
Since all HLS playlist/segments requires to append extra queries/headers before requesting to Mildom servers (usually, this is done in HLS playlist, but Mildom don't!), proxying required.    
The proxy is hosted at [Vercel](https://vercel.com/) as [bookish-octo-barnacle.vercel.app](https://bookish-octo-barnacle.vercel.app).

# Vercel has a limit
According to their [Fair Use Policy](https://vercel.com/docs/platform/fair-use-policy), Hobby plan has bandwidth limit of 100GB.    
The proxy, bookish-octo-barnacle, has served 101GB from April 1st, as of writing. Most of them caused by Mildom requests.

# Later
First of all, notify me first, before you download very much. Can be Issue here, or via Email. You can use your language if DeepL or Google Translate allows. I can host proxy at my server (or somewhere else) as an alternative for you.    
Endpoint will be temporarily disabled at 15:00 JST of April 19th (or 6:00 of same day in GMT). Download will fail at end of April. (schedule may change as yt-dlp has same extractor)

# TODO for May 1st:
- [ ] Close this issue
- [ ] also at dlp
- [ ] Enable Vercel proxy again in mildom.py
- [ ] Rewrite (technical) reason why proxy is needed (at this repo, of course)

Note that all schedules are based on JST

**Comment by nao20010128nao** [comment]
(日本語)
# 要約
VODをダウンロードする前に予告してくれ！！！！帯域オーバーだよ！！！！！！

# Mildom extractorはVercelに置いてあるプロキシで動いている
[Mildom](https://mildom.com)はHLSで動画を配信しているのはご存知のことかと思います(ダウンロード開始時にfragmentsだったりffmpegが起動するのはそれが理由です)。    
これらのHLSプレイリスト/セグメントは、HTTPリクエストを投げる前に特定のクエリとヘッダを付加しなければならず、このためだけに[Vercelでプロキシを動かしています](https://bookish-octo-barnacle.vercel.app)。

# Vercelにも限りがある
Vercelの[Fair Use Policy](https://vercel.com/docs/platform/fair-use-policy)によると、Hobbyプランでは100GBの帯域制限があります。    
プロキシ(bookish-octo-barnacle)は4/1からこのIssueを立てた時点で累計101GBを配信しており、そのトラフィックのほとんどがMildomのリクエストです。

# お願いと今後
何よりも、大量ダウンロードするなら予告して下さい。Issueでも良いです。メールでも良いです。DeepLかGoogle翻訳が使えるなら自国語で書いていいです。何か対応策を提示します。    
なお、プロキシは4/19 日本時間15:00を以って、月末まで一時的に封印します。(同じMildom extractorのあるyt-dlpとの折衝が必要なため、スケジュールが変更になる可能性があります。)

**Comment by nao20010128nao** [comment]
Please update ytdl-patched to latest using `youtube-dl -U`, newest version avoids using Vercel.
